baseURL = "http://zhuangbi.student.ust.hk/portfolio/"
languageCode = "en-us"
title = "HUANG Zeyu's Personal Portfolio"
theme = "forty"

[params]
    name = "Huang Zeyu"
    description = "Huang Zeyu's personal portfolio page"

    [params.navigation]
        title = "Huang Zeyu's"
        subtitle = "Personal Portfolio"
        menu = "Menu"

        [[params.navigation.links]]
            name = "Yu"
            url = "https://medium.com/@huang.zeyu/course-project-an-app-prototype-that-makes-it-easier-to-teach-your-grandma-how-to-use-a-d512dfff0e0f"

        [[params.navigation.links]]
            name = "Cool Cook"
            url = "posts/cool-cook"

        [[params.navigation.links]]
            name = "Stab Project"
            url = "#"

        [[params.navigation.links]]
            name = "Stab Project"
            url = "#"

    [params.banner]
        title = "Hi, my name is Huang Zeyu."
        subtitle = """Welcome to my personal portfolio page.
        In Chinese, surname comes first. You can call me Zeyu."""

    [params.tiles]
        enable = true
        [[params.tiles.showcase]]
            title = "Yu - app prototype"
            subtitle = "An app prototype that makes it easier to teach your grandma how to use a smartphone, without losing your sanity"
            image = "yu.png"
            url = "https://medium.com/@huang.zeyu/course-project-an-app-prototype-that-makes-it-easier-to-teach-your-grandma-how-to-use-a-d512dfff0e0f"
        [[params.tiles.showcase]]
            title = "Cool Cook - chatbot prototype"
            subtitle = "A chatbot prototype that guides you through a cooking workflow that makes the most sense"
            image = "coolcook.png"
            url = "posts/cool-cook"
        [[params.tiles.showcase]]
            title = "Stab Project"
            subtitle = "Coming soon..."
            image = "pic2.jpg"
            url = "#"
        [[params.tiles.showcase]]
            title = "Stab Project"
            subtitle = "Coming soon..."
            image = "pic3.jpg"
            url = "#"
    # [params.two]
    #     enable = true
    #     title = "Massa libero"
    #     subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    #     Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    #     Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    #     Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    #     Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    #     buttonText = "Get Started"
    #     url = "blogs"
    [params.footer]
        enable = true
        copyright = "Zeyu Huang"

        [[params.footer.social]]
            icon = "fa-github"
            url= "https://www.github.com/fhfuih"
            label = "GitHub"

        [[params.footer.social]]
            icon = "fa-facebook"
            url= "https://www.facebook.com/fhfuih.hzy"
            label = "Facebook"

        # [[params.footer.social]]
        #     icon = "fa-instagram"
        #     url= "https://www.instagram.com"
        #     label = "Instagram"

        [[params.footer.social]]
            icon = "fa-linkedin"
            url= "https://www.linkedin.com/in/zeyu-huang-522a52178/"
            label = "LinkedIn"
